version: '3.8'

services:
  postgres:
    image: postgres:15.3
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin             # 'admin' user
      POSTGRES_PASSWORD: admin         # 'admin' password
      POSTGRES_DB: market              # The 'market' database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d  # Initialize scripts for admin role and permissions
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: